# Site settings
title: Developer Documentation
email: support@xappmedia.com
description: > # this means to ignore newlines until "baseurl:"
  Documentation for all XAPPmedia developer products
url: "http://developer.xappmedia.com" # the base hostname & protocol for your site
twitter_username: xappmedia
github_username:  xappmedia
source_repository: https://github.com/XappMedia/Documentation
excerpt_separator: <!--more-->

# API Variables
ios_api_current: /ios/api
android_api_current: /android/api

# Collections
collections:
  ios:
    output: true
  android:
    output: true
  guides:
    output: true

markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

permalink: /articles/:year/:month/:day/:title/

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]
